name: Deploy to Staging
on: workflow_dispatch

jobs:
  deploy:
    uses: sajmoni/alchemy/.github/workflows/deploy.yml@main
    with:
      game_name: rymdkraftverk/big-blue-brawls:web
    secrets:
      BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
